config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'pages/contact'
  get "about", to: "pages#about"
  get 'pages/home'
  get "error", to: "pages#error"

  get "blog", to: redirect('https://www.linkedin.com/in/sthrupesh/')

  resources :projects do
    resources :tasks, except: [:index], controller: 'projects/tasks'
  end

  root 'pages#home'

  # get "*path", to: redirect("/error")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/counter.rb
class Counter
  def self.calculate_percent_complete(completed_tasks, total_tasks)
    completed_tasks.to_f / total_tasks.to_f * 100
  end
end

app/models/project.rb
class Project < ApplicationRecord
  # Define relationship with task
  has_many :tasks

  # Add default column values
  after_initialize :set_defaults

  # Validation
  validates_presence_of :title, :description

  # Custom scoping
  scope :almost_completed, -> { where('percent_complete > 75.0') }
  scope :still_needs_some_work, -> { where('percent_complete < 75.0') }

  def set_defaults
    self.percent_complete ||= 0.0 # if value is nil set to 0 else don't do anything
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  after_save :update_percent_complete if :mark_completed?

  scope :completed, -> { where(completed: true) }

  scope :not_completed, -> { where(completed: false) }

  mount_uploader :task_file, TaskFileUploader

  def mark_completed?
    self.completed == true
  end

  def update_percent_complete
    project = Project.find(self.project_id)
    count_of_completed_tasks = project.tasks.completed.count
    count_of_total_tasks = project.tasks.count
    project.update!(percent_complete: Counter.calculate_percent_complete(count_of_completed_tasks, count_of_total_tasks))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def foo
    p "Hey from the application controller"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
    @title = "My cool title"
  end

  def home
    @title = "Welcome to home!!!"
    @projects = Project.all
    @table_headers = ['Title', 'Description', 'Percentage Completed', "Action"]
  end

  def error

  end
end

app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :new, :edit, :create, :destroy, :update]

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.project_id = @project.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_url(@task.project_id), notice: "Task created successfully" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_url(@task.project_id), notice: "Task updated successfully" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@task.project_id), notice: "Task deleted successfully" }
      format.json { head :no_content }
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :project_id, :completed, :task_file)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.still_needs_some_work
  end

  # GET /projects/1 or /projects/1.json
  def show
    @tasks = @project.tasks
    @tasks_headers = ['Title', 'Description', 'Attachment', 'Completed', 'Actions']
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:title, :description, :percent_complete)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task created successfully" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task updated successfully" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@task.project_id), notice: "Task deleted successfully" }
      format.json { head :no_content }
    end
  end

  private

  def set_task

  end

  def task_params

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taski</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="bg-primary text-primary">
<%= render "shared/nav" %>
<%= render "shared/alerts" %>

<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<p><%= @title %></p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/error.html.erb
<h1>Sorry, that page does not exist!</h1>

Go back to <%= link_to "homepage", root_path %>

app/views/pages/home.html.erb
<div class="homepage-projects">
  <div class="container">
    <% if current_user %>
      <%= render "shared/project/projects" %>
    <% else %>
      <div class="center-div">
        <h1>Welcome to Taski!</h1>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :percent_complete, style: "display: block" %>
    <%= form.text_field :percent_complete %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Percent complete:</strong>
    <%= project.percent_complete %>
  </p>

</div>

app/views/projects/edit.html.erb
<div style="padding-left: 10%; padding-right: 10%">
  <div>
    <div class="title" style="margin-bottom: 2rem">Edit project</div>

    <%= render "form", project: @project %>

    <br>

    <div>
      <%= link_to "Show this project", @project %> |
      <%= link_to "Back to projects", pages_home_path %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<div style="padding-right: 5%; padding-left: 5%; padding-top: 5%">
  <div>
    <h1>New project</h1>

    <%= render "form", project: @project %>

    <br>

    <div>
      <%= link_to "Back to project", pages_home_path %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="project-detail-container">
  <%= render "shared/project/project_summary" %>

  <hr>
  <%= render 'shared/tasks/tasks_table' %>
  <div style="margin-top: 2rem">
    <%= link_to "Add a new task for this project", new_project_task_path(project_id: @project.id) %>
  </div>
</div>

app/views/projects/tasks/_form.html.erb
<div style="padding-left: 5%; padding-right: 5%; padding-top:5%">
  <div>
    <%= form_for [@project, @task] do |f| %>
      <% if @task.errors.any? %>
        <%= pluralize(@task.errors.count, "error") %> prohibited this project from being saved:

        <% @task.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :completed %>
      <%= f.check_box :completed %>

      <%= f.label :Attachment %>
      <%= f.file_field :task_file %>

      <%= f.submit %>


    <% end %>
  </div>
</div>

app/views/projects/tasks/edit.html.erb
<%= render 'form' %>

app/views/projects/tasks/new.html.erb
<div class="new-task-container">
  <p class="title">
    Create a new task
  </p>
  <%= render 'form' %>

</div>

app/views/projects/tasks/show.html.erb
<hr>
<h3><%= @task.title %></h3>

<p><%= @task.description %></p>
<h4>
  Task started: <%= @task.created_at %>
</h4>
<% if @task.created_at != @task.updated_at %>
  <h4>
    Updated: <%= @task.updated_at %>
  </h4>
<% end %>

<% if @task.completed == true %>
  <p><em>Task is completed</em></p>
<% else %>
  <p><em>Task is pending</em></p>
<% end %>

<%# unless @task_file.blank? %>
<p><%= link_to "Attachment", @task.task_file.to_s %></p>
<%# end %>

<%= link_to "Edit", edit_project_task_path(@task.project_id, @task.id) %>

<%= link_to "Back to project", project_path(@task.project_id) %>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_nav.html.erb
<div class="nav-section bg-secondary text-secondary">
  <span class="nav-item"><%= image_tag("logos/logo.png", height: 50, width: 50) %></span>
  <div class="text-secondary">
    <% if current_user %>
      <%= link_to "Home", root_path, class: "nav-item" %>
      <%= link_to "Edit account", edit_user_registration_path, class: "nav-item" %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "nav-item" %>
      <% else %><%= link_to "Sign in", new_user_session_path, class: "nav-item" %><%= link_to "Sign up", new_user_registration_path, class: "nav-item" %>
    <% end %>
  </div>
</div>

app/views/shared/project/_project_summary.html.erb
<div style="display: flex; align-items: center">
  <p class="project-title"> <%= @project.title %> <%= " | " %> </p>
  <%= link_to 'Edit', edit_project_path(@project) %>

</div>
<div>
  <p class="project-fields-header">Description</p>
  <p class="project-description"><%= @project.description %></p>
</div>

<div>
  <p class="project-fields-header">Completed: <%= @project.percent_complete %>%</p>
</div>

app/views/shared/project/_projects.html.erb
<div style="display: flex; justify-content: space-between; align-items: center">
  <h2>Projects</h2>

  <%=
    link_to "Create a new project", new_project_path %>
</div>
<table class="project-table">
  <tr class="bg-light-green">
    <% @table_headers.each do |header| %>
      <th>
        <p class="text-header"> <%= header %></p>
      </th>
    <% end %>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <td>
        <p class="text-row"><%= project.title %></p>
      </td>
      <td>
        <p class="text-row"><%= project.description %></p>
      </td>
      <td>
        <p class="text-row"><%= "#{project.percent_complete} %" if project.percent_complete %></p>
      </td>
      <td>
        <div>
          <%= link_to "Edit", edit_project_path(project.id) %> |
          <%=
            link_to "View", project_url(project.id) %>

        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/shared/tasks/_tasks_table.html.erb
<h2>Tasks</h2>
<table class="project-table">
  <tr class="bg-light-green">
    <% @tasks_headers.each do |header| %>
      <th>
        <p class="text-header"> <%= header %></p>
      </th>
    <% end %>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <td>
        <p class="text-row"><%= task.title %></p>
      </td>
      <td>
        <p class="text-row"><%= task.description %></p>
      </td>
      <td>
        <p><%= link_to "attachment", task.task_file.to_s, target: :'_blank' %></p>
      </td>
      <td>
        <p class="text-row"><%= "Yes" if task.completed %><%= "No" unless task.completed %></p>
      </td>
      <td>
        <div>
          <%= link_to "Edit", edit_project_task_path(task.id) %> |
          <%=
            link_to "View", project_task_path(task.id) %>
        </div>
      </td>
    </tr>
  <% end %>
</table>